service: eb-sqs-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action: events:PutEvents
          Resource: !GetAtt EventBus.Arn 

functions:
  putEventsLambda:
    handler: functions/putEvents.handler
    environment:
      EventBusName: !Ref EventBus
    events:
      - http:
          method: post
          path: /generate

resources:
  Resources: ${file(resources.yml)}
  Outputs:
    EventBusName:
      Value: !Ref EventBus

